version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: images_processing
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: images-processing
      POSTGRES_USER: images
      POSTGRES_PASSWORD: images
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-images
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"